### ISSUE TITLE
cannot run after upgrading rvm/jruby

### ISSUE THREAD

**Issue by jmazzitelli** [pilhuhn/hawkfx#37]
I have two Fedora 23 machines. One upgraded OK, the other did not. I cannot run hawkfx on this laptop of mine.

```
$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

```
$ rvm use jruby-9.1.5.0
Using /home/mazz/.rvm/gems/jruby-9.1.5.0
```

```
$ bundle install
Using rake 10.5.0
Using concurrent-ruby 1.0.5 (java)
Using i18n 0.8.1
Using minitest 5.10.1
Using thread_safe 0.3.6 (java)
Using public_suffix 2.0.5
Using ast 2.3.0
Using safe_yaml 1.0.4
Using diff-lcs 1.3
Using unf 0.1.4 (java)
Using event_emitter 0.2.5
Using hashdiff 0.3.2
Using mime-types-data 3.2016.0521
Using netrc 0.11.0
Using websocket 1.2.4
Using jruby-openssl 0.9.20 (java)
Using jrubyfx-fxmlloader 0.4.1 (java)
Using polyglot 0.3.5
Using powerpack 0.1.1
Using rainbow 2.2.1
Using rspec-support 3.5.0
Using ruby-progressbar 1.8.1
Using unicode-display_width 1.1.3
Using shoulda-context 1.2.2
Using simple-websocket-vcr 0.0.4
Using vcr 3.0.3
Using yard 0.9.8
Using bundler 1.14.6
Using tzinfo 1.2.2
Using addressable 2.5.0
Using parser 2.4.0.0
Using crack 0.4.3
Using domain_name 0.5.20170223
Using mime-types 3.1
Using websocket-client-simple 0.3.0
Using jrubyfx 1.2.0 (java)
Using treetop 1.6.8
Using rspec-core 3.5.4
Using rspec-expectations 3.5.0
Using rspec-mocks 3.5.0
Using activesupport 5.0.2
Using rubocop 0.41.2
Using webmock 2.3.2
Using http-cookie 1.0.3
Using rspec 3.5.0
Using shoulda-matchers 2.8.0
Using rest-client 2.0.1
Using shoulda 3.5.0
Using hawkular-client 2.8.0
Bundle complete! 16 Gemfile dependencies, 49 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

But when I try to run:

```
$ jruby -G -S hawkfx.rb
libGL error: failed to open drm device: Permission denied
libGL error: failed to load driver: nouveau
/home/mazz/.rvm/gems/jruby-9.1.5.0/gems/jrubyfx-fxmlloader-0.4.1-java/lib/fxmlloader/elts.rb:158: warning: `<<' after local variable or literal is interpreted as binary operator
/home/mazz/.rvm/gems/jruby-9.1.5.0/gems/jrubyfx-fxmlloader-0.4.1-java/lib/fxmlloader/elts.rb:158: warning: even though it seems like here document
Exception running Application:
#<NameError: uninitialized constant ValueElement::Logging
Did you mean?  Logger>
org/jruby/RubyModule.java:3346:in `const_missing'
/home/mazz/.rvm/gems/jruby-9.1.5.0/gems/jrubyfx-fxmlloader-0.4.1-java/lib/fxmlloader/value_elts.rb:149:in `processValue'
/home/mazz/.rvm/gems/jruby-9.1.5.0/gems/jrubyfx-fxmlloader-0.4.1-java/lib/fxmlloader/value_elts.rb:67:in `processStartElement'
/home/mazz/.rvm/gems/jruby-9.1.5.0/gems/jrubyfx-fxmlloader-0.4.1-java/lib/jrubyfx-fxmlloader.rb:440:in `processStartElement'
/home/mazz/.rvm/gems/jruby-9.1.5.0/gems/jrubyfx-fxmlloader-0.4.1-java/lib/jrubyfx-fxmlloader.rb:351:in `load'
/home/mazz/.rvm/gems/jruby-9.1.5.0/gems/jrubyfx-1.2.0-java/lib/jrubyfx/controller.rb:129:in `load_into'
/home/mazz/.rvm/gems/jruby-9.1.5.0/gems/jrubyfx-1.2.0-java/lib/jrubyfx/core_ext/stage.rb:82:in `fxml'
hawkfx.rb:18:in `block in start'
org/jruby/RubyBasicObject.java:1667:in `instance_eval'
/home/mazz/.rvm/gems/jruby-9.1.5.0/gems/jrubyfx-1.2.0-java/lib/jrubyfx/module.rb:49:in `with'
hawkfx.rb:17:in `start'
/home/mazz/.rvm/gems/jruby-9.1.5.0/gems/jrubyfx-1.2.0-java/lib/jrubyfx/java_fx_impl.rb:119:in `block in launch_app_after_platform'
```

**Comment by pilhuhn** [comment]
On 28 Mar 2017, at 16:54, John Mazzitelli wrote:

> I have two Fedora 23 machines. One upgraded OK, the other did not. I 
> cannot run hawkfx on this laptop of mine.
>
> ```
> $ java -version
> java version "1.8.0_45"

This is waaaaay too old. See README.adoc.
You should also run _121 or such for all the security fixes since _45

**Comment by jmazzitelli** [comment]
Thanks. That was the problem. All better now once I moved to latest JRE:

```
$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```
